# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url: "/"
    weight: 10

  - name: 加入我们
    url: contact
    weight: 20

  - name: 研究
    url: project
    weight: 30

  - name: 论文
    url: publication
    weight: 40

  - name: 报告
    url: talk
    weight: 50

  - name: 课程
    url: course
    weight: 60
    identifier: courses

  - name: 成员
    url: people
    weight: 70
  # - name: 英文网
  #   url: 'https://TsangEyan.github.io/'
  #   weight: 70
