# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: Rose
  theme_night: Rose
  font: Minimal
  font_size: l

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ""
    org_name: ""
    description: "A highly-customizable Hugo research group theme powered by Wowchemy website builder."
    twitter: "wowchemy"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
  verification:
    google: ""
    baidu: ""

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice:
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false
  icp:
    enable: true
    text: "浙ICP备2025148205号"
    link: "https://beian.miit.gov.cn"
  police:
    enable: true
    text: "浙公网安备33010602013851号"
    link: "https://beian.mps.gov.cn/#/query/webSearch?code=33010602013851"

# Localization

locale:
  date_format: ""
  time_format: ""
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/<username>/<repository>"
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ""
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: "mapnik"
    api_key: ""
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
# Citation style

# publications:
#   date_format: January 2006
#   citation_style: apa
